language: node_js
node_js:
- 6
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - gcc
    - make
    - cmake
    - git-crypt
before_install:
- openssl aes-256-cbc -K $encrypted_9b2a275b7417_key -iv $encrypted_9b2a275b7417_iv -in git-crypt-key.key.enc -out git-crypt-key.key -d
before_script:
- npm install -g gulp particle-cli
- particle login $PARTICLE_USER $PARTICLE_PWD
- git crypt unlock git-crypt-key.key
script: gulp travis
env:
  global:
  - secure: aQd1q7J6gyvBBgccwh4ugZ0loJ3QqbuZ1S/qtaQZYzQCcfZDVqycF5TdOdEVxzokyraCdGJTkH033me71tz/LlvXw5Q32FAg/hJrC9uUJcfEf6UbNp5MnTMwzci70ULfJgNQXJQtfZouR9DFmTzm66suYFKoZAVQhOGI4gBkuz0qzp2qDNID7k93BO3hOTWG/iDedz+3hhPKbBfTMDGrSTwYI7B6N/1IfxEUExYEutFNnxawM/RR2nLLcm52BTzSqcI3M4zzbbGzGRipsDXNfNblLxtKHcHPDiIJTOH2KVwvqPQdrw2WjgKOySXwpzOoDpelW5E38HGT3qwQW/El+MEcZiDWgR/EpoEaF0A3yMfB5m0FzCyE688dkgXSZ+fToaoTDhhnpFyHGMx9kAMI2jRDJ2UDM4F9jp56UYLG2IrlT0jECrj3cV+Tt5fV7m1Ze/wsfBciv4JtmVElkCvp3vipt87z7lhkgSmC6z+WP53i4tsAEgz55gKwVJhDNEQP1d9R0mxZ2/M5COolngwIabf4erMQVwSgcpjyY8pLo73rv8/JjsFR/t0tWXfmdOQ81OYkx2tUG4khvlB5lMEiqnPfQk/kw+vmi9KFgTDM2pB6NMUiqF42nWFVUAtZuCCiFU0FXZxcniy6oa872BxMzzDEta6N/bNeDNhDoLGf5qE=
  - secure: qvB8A+kRKe7JL88/bduArbVCM8sIsHmRgtyz8Vsph92plRwMklduR0g/hQ8eFK3TMMit5v8qC2dJH7fZ+8eZ4l29ZXkIFx+Nch/ciQhpSF9Dce1Gy/47FPAJqeGrbXiTwO59VqwBehOsCXjKN1bpppGXJTyBLWlZfMITyG/6miUTdrKsT4H7/Lq1STxSAHExpHiecdE+ELIoUpp4lPzpVUzXy6VAIDKeI2dAQr1BpkOqLySXiOHPmCGKlYSm7O9PucV7I1jR9RUHsP1pYqyevTZNWgesRKZ5tkYPK3PF1zu8xxFWWJey0L4sjurDGJN3sVxOWVXimKzYFMQcTb6fv49p2FuGtK7NPJTgWZw7YHuYek/laIF9Bk1Dwaa1hZX4od/bvTQur3lLVtNlZg06j3UK7VsN6zXQH38aVRqoR51E/ypaZ0Ryy3ANIqtqQyF92Fl+u/jzdsy1jlXFo4Gb0gihadcKM4NEG9JcD/1HHpBGOVCT0KSY3xQBedkIAv9n1ODUPwqtIxa9u9nhunoh8Mn9ddg7r6Dfw9RJTf3rBIrykkIhuHs4OBPWcu6ctVnF/3FZoij64JHcrDFW5pUt9FRNTsxUuQICP6p99Yih25H+7LLI7HMDLTa6DKBBfSqLAILxH+VzdBLKirlJiPsM3MODZT7nXO+Ou754RoRkFUU=

